FROM python:3.11-slim

WORKDIR /app
COPY pyproject.toml ./
RUN pip install --no-cache-dir poetry && poetry config virtualenvs.create false && poetry install --only main --no-interaction --no-ansi
COPY apps ./apps
COPY packages ./packages

CMD ["python", "-m", "apps.data_worker.main"]
